// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/angel-theater-map/Current.tsx": () => import("../components/mockups/angel-theater-map/Current.tsx"),
  "./components/mockups/angel-theater-map/FocusedMap.tsx": () => import("../components/mockups/angel-theater-map/FocusedMap.tsx")
};
