/* ===========================================================================
   ANGEL SWARM — DATA PRODUCTS

   THE HOLE THIS FILLS, STATED PLAINLY.

   Until this module existed this application was a consumer and nothing else.
   It read Cursor on Target off a socket, it read its own scenario files, and
   at the end of a run everything it had computed died with the tab. A judge
   reading the interoperability criterion — "these projects consume and
   produce data products to the data catalog" — could see the consuming half
   and would find nothing at all on the producing half, because there was
   nothing to find.

   This is the producing half. It turns a run into files a different system
   could actually read: a casualty care record set shaped as FHIR R4
   resources, the decision record with its whole hash chain, the run result
   in JSON and CSV, a JSON Schema for each of those so a consumer can validate
   what it receives, and a machine-readable catalog manifest that lists every
   product this application publishes and every source it consumes.

   WHAT THIS DOES NOT CLAIM, AND THIS IS THE IMPORTANT PARAGRAPH.

   The casualty record set is FHIR-SHAPED. It is not a conformance-tested FHIR
   implementation. No FHIR validator has been run against it, no
   StructureDefinition has been checked, no terminology server has resolved a
   single code, and no profile is asserted. What is true is narrower and worth
   more than a claim we cannot support: the resources carry FHIR R4 resource
   types, elements and cardinalities as written in the specification, so a
   FHIR-literate engineer opens the file and recognises what they are looking
   at rather than having to reverse-engineer a bespoke format. Everywhere this
   product is named — in the interface, in the catalog manifest, in the file's
   own metadata and in its schema — it is named as FHIR-shaped and marked as
   not conformance-tested. Anyone who ships it as conformant has been told
   otherwise in five places.

   There is no LOINC code for compensatory reserve. Rather than borrow one
   that means something else, the compensatory-reserve Observation carries a
   local code in a urn:angel-swarm code system and says so. A borrowed code
   that a receiving system would silently mis-bind is worse than an unbound
   local one that fails loudly.

   Every identifier is synthetic. There is no real person anywhere in this
   file, the casualty stream is generated by the engine from a seed, and every
   resource carries the HL7 HTEST security label — the standard's own marking
   for test health data — so a system that ingested one by accident would know
   what it had.

   THE TRANSMISSION BOUNDARY. This application PRODUCES the record. It does
   not TRANSMIT it. Everything below is generated in this browser and handed
   to the operator as a file over a blob URL; no request leaves this origin,
   there is no client for OMDS, there is no client for MHS GENESIS, and this
   module opens no socket. The vertical path a fielded system would take —
   point of injury, into OMDS, into the MHS GENESIS longitudinal record — is
   documented on the Data Products tab because it is the path this record is
   shaped for, not because this build walks it.

   UNCLASSIFIED // SYNTHETIC DATA // FOR DEMONSTRATION ONLY
   ========================================================================= */
(function () {
  'use strict';

  /* THE PRODUCT VERSION IS PART OF EVERY FILE AND EVERY SCHEMA $id. A
     consumer that pins a schema needs to know when the shape moved under it,
     and a file with no version in it cannot be argued with later. */
  var VERSION = '1.0.0';
  var NS = 'urn:angel-swarm';

  /* THE EXERCISE DATE IS SYNTHETIC AND IS SAID TO BE.
     FHIR instants are calendar timestamps and the run's clock is a bare
     offset — T+0 to T+180 — displayed as 0400Z to 0700Z. So the run is hung
     on a fixed synthetic date, chosen once, never read from the wall clock,
     so that the same seed produces byte-identical timestamps on every machine
     that exports it. It is not a real date and no event in this file happened
     on it. */
  var EXERCISE_DAY = Date.UTC(2026, 0, 1, 0, 0, 0);
  var CLOCK_OFFSET_MIN = 240;                 /* the app's own T+0 = 0400Z */

  function instant(tMin) {
    return new Date(EXERCISE_DAY + (CLOCK_OFFSET_MIN + tMin) * 60000).toISOString();
  }
  function zulu(tMin) {
    var z = CLOCK_OFFSET_MIN + tMin, p = function (n) { return String(n).padStart(2, '0'); };
    return p(Math.floor(z / 60)) + p(Math.floor(z % 60)) + 'Z';
  }
  function r2(x) { return Math.round(x * 100) / 100; }
  /* THE RESOURCE ID IS DERIVED FROM THE ENGINE'S OWN TRACK NUMBER AND FROM
     NOTHING ELSE. Two places in this file need to name a casualty — the
     Patient resource, which has the projected record in hand, and the
     ServiceRequest, which has only a numeric casualty id off a sortie leg.
     They must agree or every subject reference in the bundle dangles, so
     both go through here rather than each formatting the id its own way. */
  function pidOf(id) { return 'cas-' + String(id).padStart(3, '0'); }
  function r3(x) { return Math.round(x * 1000) / 1000; }

  /* ---- the context the surface hands in ---------------------------------
     This module owns no run and builds nothing on its own. The destination
     that renders the tab passes the run it is already reading, folded at the
     minute it is already showing, so a product can never disagree with the
     screen it was exported from. */
  var CTX = null;
  function setContext(c) { CTX = c; }
  function ready() { return !!(CTX && CTX.run && CTX.frame); }

  /* The fold horizon. The engine's own snapshot opens the fold out to the
     whole closed record once the run reaches its horizon, because
     administrations and finalize() both stamp times at or past it. Products
     fold on exactly the same rule, so an export at T+180 carries the closed
     run and an export at T+90 carries the run as it stood at T+90. */
  function horizon() {
    var d = CTX.run._scn ? CTX.run._scn.durationMin : 180;
    return CTX.t >= d ? Infinity : CTX.t;
  }
  function survivable(c) { return c.cls === 'IMMEDIATE' || c.cls === 'DELAYED'; }

  /* ======================================================== ARM RESULTS ==
     All three arms are counted by ONE method over each arm's own casualty
     ledger, rather than by reading three differently-derived figures off
     three different places. That is the only way the three numbers on a
     scoreboard can be compared without a footnote. The blood figures come
     from the frame's own tally, which is the engine's ledger fold; the third
     arm flies nothing, so its blood columns are zero by construction rather
     than by omission. */
  function armResult(arm, meta, tq, tally) {
    var cas = arm.cas || [], i, c;
    var admitted = 0, cohort = 0, deaths = 0, survDeaths = 0, survSaved = 0, treated = 0;
    for (i = 0; i < cas.length; i++) {
      c = cas[i];
      if (c.tInjury > CTX.t) continue;
      admitted++;
      var sv = survivable(c);
      if (sv) cohort++;
      var resolved = c.tResolved != null && c.tResolved <= tq;
      if (resolved) {
        if (c.outcome === 'DIED') { deaths++; if (sv) survDeaths++; }
        else if (sv) survSaved++;
      }
      if (c.treated && c.tTreated != null && c.tTreated <= tq) treated++;
    }
    var sorties = 0;
    if (arm.sorties) for (i = 0; i < arm.sorties.length; i++) if (arm.sorties[i].tLaunch <= tq) sorties++;
    return {
      arm: meta.key, armName: meta.name,
      casualtiesAdmitted: admitted,
      survivableCohort: cohort,
      /* THE HEADLINE FIGURE. Deaths among casualties whose wounds were
         survivable with the intervention this system delivers. Red on every
         arm on every screen in this application, because a death is a death
         whichever tasking produced it or failed to. */
      survivableDeaths: survDeaths,
      survivableSaved: survSaved,
      deathsAllCategories: deaths,
      sortiesFlown: sorties,
      administrations: treated,
      bloodUnitsIssued: tally ? tally.bloodIssued : 0,
      bloodUnitsTransfused: tally ? tally.bloodUsed : 0,
      bloodUnitsDestroyed: tally ? tally.bloodDestroyed : 0
    };
  }

  function results() {
    var run = CTX.run, f = CTX.frame, tq = horizon(), A = CTX.arms;
    return [
      armResult(run.A, A.A, tq, f.tA),
      armResult(run.B, A.B, tq, f.tB),
      /* NO FORWARD DELIVERY has no fleet and no blood ledger to fold, which
         is the whole point of the arm. Null rather than a fabricated tally. */
      armResult(run.C, A.C, tq, null)
    ];
  }

  function runHeader() {
    return {
      scenario: CTX.run.scenario,
      joa: CTX.joa,
      theater: CTX.theater,
      seed: CTX.run.seed,
      posture: CTX.deployed ? 'ANGEL SWARM DEPLOYED' : 'NOT DEPLOYED',
      controlFairness: CTX.mode || 'fair',
      foldedAtMinute: r2(CTX.t),
      foldedAtZulu: zulu(CTX.t),
      durationMinutes: CTX.run._scn ? CTX.run._scn.durationMin : 180,
      exerciseInstant: instant(CTX.t)
    };
  }

  /* The block every product carries at its head. If one of these files is
     ever separated from this application — mailed, dropped in a share, pasted
     into a ticket — the caveats have to travel inside it, because they will
     not travel beside it. */
  function provenance(extra) {
    var p = {
      publisher: 'ANGEL SWARM — physiological-deadline blood allocation prototype',
      productVersion: VERSION,
      classification: 'UNCLASSIFIED // SYNTHETIC DATA // FOR DEMONSTRATION ONLY',
      dataNature: 'EXERCISE DATA. Every casualty, identifier, timestamp and reading below is generated by this application’s simulation engine from a seed. No real person is described here and no real event is recorded.',
      generatedBy: 'app/js/dataproducts.js, in the operator’s browser',
      transmission: 'This application produced this record. It did not transmit it. Nothing left this application’s origin to make this file.'
    };
    if (extra) for (var k in extra) p[k] = extra[k];
    return p;
  }

  /* ==================================================== FHIR-SHAPED SET ==
     Four resource types, which are the four things a run actually records:
     a Patient per casualty, an Observation per compensatory-reserve reading,
     a ServiceRequest per tasking decision and a Procedure per administration.

     WHY ServiceRequest AND NOT Task. Both were candidates. A tasking decision
     here is an order for a specific product to be delivered to a specific
     casualty by a specific airframe, authored at a specific minute — that is
     a request for service, and ServiceRequest carries intent, priority,
     authoredOn, occurrence and reasonCode without any of them being a stretch.
     Task models the workflow state of doing something about a request, which
     is a second layer this run does not separately record. One resource, no
     invented layer.

     WHY THE CODES ARE LOCAL. There is no LOINC code for compensatory reserve
     and there is no established code for "one unit of low-titer O whole blood
     delivered by unmanned aircraft to a point of injury". Borrowing a code
     that means something adjacent would make a receiving system bind the data
     to the wrong concept silently, which is the worst available outcome. Each
     code below is local to a urn:angel-swarm code system and every resource
     says so. Binding them to real terminology is work a fielding programme
     would do with a terminologist; it is not work to guess at here. */

  var HTEST = {
    system: 'http://terminology.hl7.org/CodeSystem/v3-ActReason',
    code: 'HTEST',
    display: 'test health data'
  };
  var SHAPED_TAG = {
    system: NS + ':codesystem:provenance',
    code: 'FHIR-SHAPED-NOT-CONFORMANCE-TESTED',
    display: 'FHIR-shaped. Not a conformance-tested FHIR implementation: no validator, no StructureDefinition check, no terminology binding, no profile asserted.'
  };

  var PROC_CODE = {
    BLOOD:      { code: 'ADMIN-LTOWB', display: 'Transfusion of low-titer O whole blood, 1 unit, prehospital' },
    PLASMA:     { code: 'ADMIN-FDP',   display: 'Administration of freeze-dried plasma, prehospital' },
    TXA:        { code: 'ADMIN-TXA',   display: 'Administration of tranexamic acid 2 g, prehospital' },
    TQ_KIT:     { code: 'ADMIN-HK',    display: 'Application of haemorrhage control kit — tourniquet and haemostatic gauze' },
    CHEST_SEAL: { code: 'ADMIN-CS',    display: 'Application of vented chest seal and nasopharyngeal airway' }
  };

  function payloadLabel(k) {
    var P = CTX.E && CTX.E.PAYLOADS ? CTX.E.PAYLOADS[k] : null;
    return P ? P.label : k;
  }
  function payloadShort(k) {
    var P = CTX.E && CTX.E.PAYLOADS ? CTX.E.PAYLOADS[k] : null;
    return P ? P.short : k;
  }

  function fhirBundle() {
    var run = CTX.run, A = run.A, tq = horizon(), entries = [];
    var raw = A._raw && A._raw.casualties ? A._raw.casualties : [];
    var rawById = new Map();
    for (var i = 0; i < raw.length; i++) rawById.set(raw[i].id, raw[i]);
    var droneById = new Map();
    for (i = 0; i < A.drones.length; i++) droneById.set(A.drones[i].id, A.drones[i]);

    var nObs = 0, nSR = 0, nProc = 0, nPat = 0;

    function push(res) {
      entries.push({ fullUrl: NS + ':' + res.resourceType + ':' + res.id, resource: res });
    }

    for (i = 0; i < A.cas.length; i++) {
      var c = A.cas[i];
      if (c.tInjury > CTX.t) continue;              /* nothing from the future */
      var pid = pidOf(c.id);

      /* ---- Patient. Synthetic throughout. There is no name element and
         there never will be one: the engine has no names, and inventing a
         plausible one would be the single easiest thing in this file to
         mistake for real data. What identifies the casualty is the exercise
         track number the tactical network already uses. */
      push({
        resourceType: 'Patient',
        id: pid,
        meta: { security: [HTEST], tag: [SHAPED_TAG] },
        identifier: [{
          use: 'usual',
          system: NS + ':exercise:casualty-track',
          value: c.cid,
          assigner: { display: 'ANGEL SWARM exercise, scenario ' + run.scenario + ', seed ' + run.seed }
        }],
        active: false,
        managingOrganization: { display: c.unit + ' — ' + c.site }
      });
      nPat++;

      /* ---- Observations. One per compensatory-reserve burst the tasking
         layer actually received for this casualty.

         THE BUFFER IS CAPPED AND THAT IS SAID OUT LOUD. The engine's device
         model keeps the most recent 40 bursts per casualty and drops the
         rest, which is what a real end-user device with a small ring buffer
         does. So for a long-lived casualty the earliest readings are simply
         not in this application's memory to export, and the product declares
         the cap rather than presenting a truncated series as a complete one. */
      var rc = rawById.get(c.id);
      var tele = rc && rc.tele ? rc.tele : [];
      for (var j = 0; j < tele.length; j++) {
        var b = tele[j];
        if (b.t > tq) continue;
        push({
          resourceType: 'Observation',
          id: pid + '-crm-' + j,
          meta: { security: [HTEST], tag: [SHAPED_TAG] },
          status: 'final',
          category: [{ coding: [{
            system: 'http://terminology.hl7.org/CodeSystem/observation-category',
            code: 'vital-signs', display: 'Vital Signs' }] }],
          code: {
            coding: [{
              system: NS + ':codesystem:physiology',
              code: 'CRM',
              display: 'Compensatory reserve, estimated'
            }],
            text: 'Compensatory reserve, estimated. Local code — see Bundle._angelSwarm.codeSystems.'
          },
          subject: { reference: 'Patient/' + pid },
          effectiveDateTime: instant(b.t),
          valueQuantity: { value: r2(b.v), unit: '%', system: 'http://unitsofmeasure.org', code: '%' },
          interpretation: [{ coding: [{
            system: NS + ':codesystem:physiology',
            code: b.zone,
            display: 'Device reserve zone ' + b.zone }] }],
          method: { text: 'Estimated on the casualty’s own worn device.' },
          component: [{
            code: { coding: [{ system: NS + ':codesystem:physiology', code: 'SIGQ', display: 'Signal quality, 0 to 1' }] },
            valueQuantity: { value: r3(b.q), unit: '1' }
          }],
          note: [{ text: 'Burst trigger ' + b.trigger }]
        });
        nObs++;
      }
    }

    /* ---- ServiceRequests. One per tasking decision, where a tasking
       decision is one leg of one sortie: this payload, to this casualty, on
       this airframe, authored at the minute the sortie launched. A leg the
       aircraft never flew is a decision that was taken and then overtaken,
       so it is present with status revoked and the reason on it — dropping
       it would make the record show only the taskings that worked out. */
    for (i = 0; i < A.sorties.length; i++) {
      var so = A.sorties[i];
      if (so.tLaunch > tq) continue;
      var d = droneById.get(so.droneId);
      for (j = 0; j < so.stops.length; j++) {
        var stop = so.stops[j];
        var sid = 'srt-' + so.id + '-leg-' + (j + 1);
        var target = pidOf(stop.casId);
        var done = !stop.fail;
        push({
          resourceType: 'ServiceRequest',
          id: sid,
          meta: { security: [HTEST], tag: [SHAPED_TAG] },
          identifier: [{ system: NS + ':exercise:sortie-leg', value: sid }],
          status: done ? 'completed' : 'revoked',
          intent: 'order',
          priority: 'stat',
          code: {
            coding: [{
              system: NS + ':codesystem:tasking',
              code: 'DELIVER-' + payloadShort(stop.payload),
              display: 'Deliver ' + payloadLabel(stop.payload) + ' to point of injury by unmanned aircraft'
            }]
          },
          subject: { reference: 'Patient/' + target },
          authoredOn: instant(so.tLaunch),
          occurrenceDateTime: instant(stop.arrive != null ? stop.arrive : so.tLaunch),
          requester: {
            display: so.actor === 'STANDING AUTHORITY'
              ? 'ANGEL SWARM allocator, acting inside standing authority'
              : 'ANGEL SWARM allocator, after human authorisation (' + so.actor + ')'
          },
          performer: [{ display: (d ? d.call + ' · ' + d.platLabel : 'airframe ' + so.droneId) }],
          reasonCode: [{ text: 'Physiological-deadline tasking: the casualty’s compensatory reserve put them inside a deadline this airframe could meet.' }],
          note: done ? undefined : [{ text: 'Not delivered: ' + stop.fail + (stop.overtaken ? ' (the casualty resolved before the aircraft arrived).' : '.') }]
        });
        nSR++;

        /* ---- Procedure. One per administration that actually happened. The
           administering clinician is the responder who was already on the
           ground; this system delivers the product, it does not perform the
           procedure, and the record says which. */
        if (done && stop.tAdmin != null && stop.tAdmin <= tq) {
          var cc = A._byId ? A._byId.get(stop.casId) : null;
          var pc = PROC_CODE[stop.payload] || { code: 'ADMIN-' + stop.payload, display: 'Administration of ' + payloadLabel(stop.payload) };
          push({
            resourceType: 'Procedure',
            id: 'proc-' + so.id + '-' + (j + 1),
            meta: { security: [HTEST], tag: [SHAPED_TAG] },
            status: 'completed',
            category: { coding: [{ system: NS + ':codesystem:procedure', code: 'PREHOSPITAL', display: 'Prehospital intervention at point of injury' }] },
            code: { coding: [{ system: NS + ':codesystem:procedure', code: pc.code, display: pc.display }] },
            subject: { reference: 'Patient/' + target },
            performedDateTime: instant(stop.tAdmin),
            basedOn: [{ reference: 'ServiceRequest/' + sid }],
            performer: [{
              actor: { display: cc ? cc.responder + ' on scene — ' + cc.responderQual : 'responder on scene' },
              function: { text: 'The responder already on the ground administered the product. ANGEL SWARM delivered it and did not administer it.' }
            }],
            note: [{ text: 'Delivered by ' + (d ? d.call + ' · ' + d.platLabel : 'airframe ' + so.droneId) + ' on sortie ' + so.id + '.' }]
          });
          nProc++;
        }
      }
    }

    var hdr = runHeader();
    return {
      resourceType: 'Bundle',
      id: 'angel-swarm-' + run.scenario.toLowerCase().replace(/_/g, '-') + '-seed' + run.seed + '-t' + Math.floor(CTX.t),
      meta: {
        lastUpdated: instant(CTX.t),
        security: [HTEST],
        tag: [SHAPED_TAG, {
          system: NS + ':codesystem:provenance',
          code: 'SYNTHETIC-EXERCISE-DATA',
          display: 'Synthetic exercise data. No real person is described.'
        }]
      },
      type: 'collection',
      timestamp: instant(CTX.t),
      total: entries.length,
      /* A DELIBERATELY NON-FHIR KEY, AND THE REASON FOR IT.
         FHIR has no element for "this is not really FHIR", so there is
         nowhere conformant to put the one sentence a reader most needs. The
         underscore-prefixed block below is not part of the specification and
         its presence is itself evidence of the claim it makes. Strip it and
         the bundle is unchanged; leave it and the caveat travels with the
         file. That trade is worth one non-conformant key. */
      _angelSwarm: provenance({
        product: 'angel-swarm.casualty-care-record',
        conformance: 'FHIR-SHAPED, NOT CONFORMANCE-TESTED. These resources use FHIR R4 resource types and element names. No FHIR validator has been run against this file, no StructureDefinition has been checked, no terminology server has resolved any code, and no profile is asserted. Do not represent this as conformant FHIR.',
        codeSystems: 'Compensatory reserve, tasking and procedure codes are local to urn:angel-swarm. There is no LOINC code for compensatory reserve; a borrowed code would bind a receiving system to the wrong concept, so none is borrowed. Each Observation carries the local code and a short text rather than repeating this paragraph a few thousand times — the caveat is stated once, here, and it governs every reading in the bundle.',
        observationMethod: 'Compensatory reserve is estimated on the casualty’s own worn device. In this exercise the estimate is produced by the simulation engine; the fielded equivalent is the CRI-Net model documented on the Sensor & Model destination. A burst reaches the tasking layer on reserve-zone change or every 45 seconds, and none at all while the link is down — the trigger is on each Observation as a note.',
        targetSystem: 'Shaped for the MHS GENESIS longitudinal record, which point-of-injury documentation reaches vertically through OMDS. This application produces the record and does not transmit it; there is no OMDS client and no MHS GENESIS client in this build.',
        telemetryBufferCap: 'The engine’s device model keeps the most recent 40 compensatory-reserve bursts per casualty. For a long-lived casualty the earliest readings are not retained and therefore are not in this file.',
        run: hdr,
        counts: { Patient: nPat, Observation: nObs, ServiceRequest: nSR, Procedure: nProc }
      }),
      entry: entries
    };
  }

  /* ================================================== THE DECISION RECORD ==
     The audit chain the run wrote, oldest first, with the WHOLE 64-character
     digest on every entry. Every screen in this application prints the first
     twelve characters and says in words that it is a prefix; this is the copy
     that carries all of it, and it is the copy anybody recomputing the chain
     should be given.

     The verification below is run here, at export, and its result is written
     into the file. A record that says "verified" without saying what was
     recomputed is a claim; this one carries the algorithm, the exact payload
     construction and the count, so a reader can redo it. */
  function decisionRecord() {
    var f = CTX.frame, chain = f.feed.slice().reverse(), i;
    var sha = CTX.sha256Hex;
    var prev = 'GENESIS', bad = [], entries = [];
    for (i = 0; i < chain.length; i++) {
      var e = chain[i];
      var payload = [e.t.toFixed(2), e.actor, e.action, e.detail].join('|');
      /* IF THERE IS NO DIGEST FUNCTION, THE ANSWER IS "NOT CHECKED", NOT
         "VERIFIED". The first draft of this returned true when the hash
         function was absent, which would have written the word verified into
         a file where nothing had been recomputed at all — precisely the kind
         of quiet lie the rest of this application exists to avoid. Null
         means not checked, and the schema allows it. */
      var recomputed = sha ? sha(prev + '|' + payload) : null;
      var ok = recomputed === null ? null : (e.prev === prev && recomputed === e.hash);
      if (ok === false) bad.push(e.seq);
      entries.push({
        seq: e.seq,
        minute: r2(e.t),
        zulu: zulu(e.t),
        instant: instant(e.t),
        actor: e.actor,
        action: e.action,
        detail: e.detail,
        previousHash: e.prev,
        hash: e.hash,
        hashVerifiedAtExport: ok
      });
      prev = e.hash;
    }
    return {
      product: 'angel-swarm.decision-record',
      _angelSwarm: provenance({
        what: 'Every decision the run took, in the order it took them, hash-linked. Escalations, standing-authority dispatches, human authorisations, administrations, wastage and losses.',
        digestPolicy: 'The full 64-character SHA-256 digest is on every entry here. The application’s own screens print the first twelve characters and say so; this file prints the whole of it.',
        limits: 'Tamper-evident, not tamper-proof. A chain recomputes only against the text it was written over; it proves that the record has not been altered since it was written, not that what was written was true.'
      }),
      run: runHeader(),
      chain: {
        algorithm: 'SHA-256',
        digestLength: 64,
        genesis: 'GENESIS',
        payloadConstruction: 'hash(n) = SHA-256( hash(n-1) + "|" + minute.toFixed(2) + "|" + actor + "|" + action + "|" + detail ), with hash(0) = the literal string GENESIS',
        entries: entries.length,
        verifiedAtExport: sha ? entries.length - bad.length : null,
        failedAtExport: sha ? bad : null,
        verificationNote: sha
          ? 'Every entry above was recomputed at export from the text printed on it and checked against the link it carries. Recompute it yourself: SHA-256 over the payload construction stated here.'
          : 'NOT CHECKED. No digest function was available to this module at export, so nothing was recomputed. The digests below are the ones the run wrote; they have not been re-verified.',
        headHash: entries.length ? entries[entries.length - 1].hash : null
      },
      entries: entries
    };
  }

  /* ======================================================== THE RESULT ====
     All three arms of one battle: the same casualties, the same weather, the
     same seed, differing only in how the intervention was allocated — and, in
     the third arm, in whether anything was delivered at all. */
  function runResult() {
    var arms = results();
    return {
      product: 'angel-swarm.run-result',
      _angelSwarm: provenance({
        what: 'The outcome of one run, on all three arms.',
        armsExplained: 'ANGEL SWARM allocates against each casualty’s physiological deadline. CURRENT — TRIAGE & PROXIMITY is the doctrinal baseline: the same aircraft and the same blood, allocated by triage category and distance. NO FORWARD DELIVERY is what the same battle costs when nothing is flown inside the window.',
        commonRandomNumbers: 'All three arms draw the same casualty stream and the same survival numbers from the same seed, so the difference between them is the allocation and nothing else.',
        deathsAreNotScored: 'Every death figure here is a death. This application counts them; it does not score them, and no arm’s toll is presented as a success.'
      }),
      run: runHeader(),
      arms: arms,
      comparison: {
        survivableDeathsAvoidedVersusBaseline: arms[1].survivableDeaths - arms[0].survivableDeaths,
        survivableDeathsAvoidedVersusNoDelivery: arms[2].survivableDeaths - arms[0].survivableDeaths,
        note: 'One seed is not a finding. The replication study on the Evidence destination is what answers whether this is luck.'
      }
    };
  }

  var RESULT_COLS = [
    'arm', 'arm_name', 'casualties_admitted', 'survivable_cohort',
    'survivable_deaths', 'survivable_saved', 'deaths_all_categories',
    'sorties_flown', 'administrations',
    'blood_units_issued', 'blood_units_transfused', 'blood_units_destroyed'
  ];
  var RESULT_KEYS = [
    'arm', 'armName', 'casualtiesAdmitted', 'survivableCohort',
    'survivableDeaths', 'survivableSaved', 'deathsAllCategories',
    'sortiesFlown', 'administrations',
    'bloodUnitsIssued', 'bloodUnitsTransfused', 'bloodUnitsDestroyed'
  ];

  function runResultCsv() {
    var arms = results(), hdr = runHeader(), lines = [];
    var q = function (v) {
      v = String(v);
      return /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v;
    };
    /* THE COMMENT LINES ARE PREFIXED WITH # AND THE PRODUCT SAYS SO.
       A CSV with a preamble breaks a naive reader that assumes row one is the
       header. The alternative — shipping the numbers with no statement that
       they are synthetic exercise data — is worse, and the schema, the
       catalog entry and the tab all state that the first six lines begin
       with # and are to be skipped. */
    lines.push('# ANGEL SWARM run result — UNCLASSIFIED // SYNTHETIC DATA // FOR DEMONSTRATION ONLY');
    lines.push('# product angel-swarm.run-result-csv version ' + VERSION + ' — six # lines precede the header row');
    lines.push('# scenario ' + hdr.scenario + ' · JOA ' + hdr.joa + ' · ' + hdr.theater + ' · seed ' + hdr.seed + ' · ' + hdr.posture);
    lines.push('# folded at T+' + hdr.foldedAtMinute + ' of ' + hdr.durationMinutes + ' minutes (' + hdr.foldedAtZulu + ')');
    lines.push('# every death figure is a death; this file counts them and does not score them');
    lines.push('# produced in the operator’s browser, transmitted nowhere');
    lines.push(RESULT_COLS.join(','));
    for (var i = 0; i < arms.length; i++) {
      lines.push(RESULT_KEYS.map(function (k) { return q(arms[i][k]); }).join(','));
    }
    return lines.join('\n') + '\n';
  }

  /* ========================================================== SCHEMAS =====
     JSON Schema draft 2020-12, one per product, so a consumer can validate
     what it receives rather than trusting that it looks right. The $schema
     value is an identifier string and is never fetched — nothing in this
     module makes a request of any kind.

     The schemas below are deliberately not exhaustive FHIR: the casualty
     record schema validates the shape THIS APPLICATION EMITS, which is a
     small, closed subset. It is not the FHIR R4 StructureDefinition and it
     does not test FHIR conformance. Passing it means the file is the file
     ANGEL SWARM meant to write; it does not mean the file is conformant FHIR,
     and the schema's own description says exactly that. */
  var DRAFT = 'https://json-schema.org/draft/2020-12/schema';

  function schemaFhir() {
    return {
      $schema: DRAFT,
      $id: NS + ':schema:casualty-care-record:' + VERSION,
      title: 'ANGEL SWARM casualty care record set (FHIR-shaped)',
      description: 'Validates the shape ANGEL SWARM emits: a FHIR R4 collection Bundle of Patient, Observation, ServiceRequest and Procedure resources. THIS IS NOT THE FHIR R4 STRUCTUREDEFINITION AND VALIDATING AGAINST IT DOES NOT TEST FHIR CONFORMANCE. The product is FHIR-shaped and has not been run through any FHIR validator.',
      type: 'object',
      required: ['resourceType', 'type', 'entry', '_angelSwarm'],
      properties: {
        resourceType: { const: 'Bundle' },
        id: { type: 'string' },
        type: { const: 'collection' },
        timestamp: { type: 'string' },
        total: { type: 'integer', minimum: 0 },
        meta: {
          type: 'object',
          properties: {
            lastUpdated: { type: 'string' },
            security: { type: 'array', items: { $ref: '#/$defs/coding' } },
            tag: { type: 'array', minItems: 1, items: { $ref: '#/$defs/coding' } }
          }
        },
        _angelSwarm: {
          type: 'object',
          description: 'Not a FHIR element. Carries the caveats so that they travel inside the file rather than beside it.',
          required: ['product', 'conformance', 'dataNature', 'run'],
          properties: {
            product: { const: 'angel-swarm.casualty-care-record' },
            conformance: { type: 'string', pattern: '^FHIR-SHAPED, NOT CONFORMANCE-TESTED' },
            dataNature: { type: 'string' },
            transmission: { type: 'string' },
            run: { $ref: '#/$defs/runHeader' },
            counts: { type: 'object' }
          }
        },
        entry: {
          type: 'array',
          items: {
            type: 'object',
            required: ['fullUrl', 'resource'],
            properties: {
              fullUrl: { type: 'string' },
              resource: {
                type: 'object',
                required: ['resourceType', 'id'],
                properties: {
                  resourceType: { enum: ['Patient', 'Observation', 'ServiceRequest', 'Procedure'] },
                  id: { type: 'string' }
                }
              }
            }
          }
        }
      },
      $defs: {
        coding: {
          type: 'object',
          required: ['system', 'code'],
          properties: { system: { type: 'string' }, code: { type: 'string' }, display: { type: 'string' } }
        },
        runHeader: runHeaderSchema()
      }
    };
  }

  function runHeaderSchema() {
    return {
      type: 'object',
      required: ['scenario', 'seed', 'foldedAtMinute', 'durationMinutes'],
      properties: {
        scenario: { type: 'string' },
        joa: { type: 'string' },
        theater: { type: 'string' },
        seed: { type: 'integer' },
        posture: { type: 'string' },
        controlFairness: { type: 'string' },
        foldedAtMinute: { type: 'number', minimum: 0 },
        foldedAtZulu: { type: 'string' },
        durationMinutes: { type: 'number', exclusiveMinimum: 0 },
        exerciseInstant: { type: 'string' }
      }
    };
  }

  function schemaDecision() {
    return {
      $schema: DRAFT,
      $id: NS + ':schema:decision-record:' + VERSION,
      title: 'ANGEL SWARM decision record',
      description: 'The hash-linked audit chain of one run, oldest entry first, with the whole 64-character SHA-256 digest on every entry.',
      type: 'object',
      required: ['product', 'run', 'chain', 'entries'],
      properties: {
        product: { const: 'angel-swarm.decision-record' },
        _angelSwarm: { type: 'object' },
        run: runHeaderSchema(),
        chain: {
          type: 'object',
          required: ['algorithm', 'digestLength', 'genesis', 'payloadConstruction', 'entries'],
          properties: {
            algorithm: { const: 'SHA-256' },
            digestLength: { const: 64 },
            genesis: { const: 'GENESIS' },
            payloadConstruction: { type: 'string' },
            entries: { type: 'integer', minimum: 0 },
            verifiedAtExport: { type: ['integer', 'null'], minimum: 0 },
            failedAtExport: { type: ['array', 'null'], items: { type: 'integer' } },
            verificationNote: { type: 'string' },
            headHash: { type: ['string', 'null'], pattern: '^[0-9a-f]{64}$' }
          }
        },
        entries: {
          type: 'array',
          items: {
            type: 'object',
            required: ['seq', 'minute', 'actor', 'action', 'detail', 'previousHash', 'hash'],
            properties: {
              seq: { type: 'integer', minimum: 1 },
              minute: { type: 'number', minimum: 0 },
              zulu: { type: 'string' },
              instant: { type: 'string' },
              actor: { type: 'string' },
              action: { type: 'string' },
              detail: { type: 'string' },
              previousHash: { type: 'string', pattern: '^(GENESIS|[0-9a-f]{64})$' },
              hash: { type: 'string', pattern: '^[0-9a-f]{64}$' },
              hashVerifiedAtExport: { type: ['boolean', 'null'], description: 'null means the entry was not re-checked at export because no digest function was available.' }
            }
          }
        }
      }
    };
  }

  function armSchema() {
    return {
      type: 'object',
      required: ['arm', 'armName', 'survivableDeaths', 'sortiesFlown'],
      properties: {
        arm: { enum: ['ANGEL', 'CURRENT', 'NODELIVERY'] },
        armName: { type: 'string' },
        casualtiesAdmitted: { type: 'integer', minimum: 0 },
        survivableCohort: { type: 'integer', minimum: 0 },
        survivableDeaths: { type: 'integer', minimum: 0 },
        survivableSaved: { type: 'integer', minimum: 0 },
        deathsAllCategories: { type: 'integer', minimum: 0 },
        sortiesFlown: { type: 'integer', minimum: 0 },
        administrations: { type: 'integer', minimum: 0 },
        bloodUnitsIssued: { type: 'integer', minimum: 0 },
        bloodUnitsTransfused: { type: 'integer', minimum: 0 },
        bloodUnitsDestroyed: { type: 'integer', minimum: 0 }
      }
    };
  }

  function schemaResult() {
    return {
      $schema: DRAFT,
      $id: NS + ':schema:run-result:' + VERSION,
      title: 'ANGEL SWARM run result',
      description: 'The outcome of one run on all three arms, folded at a stated minute.',
      type: 'object',
      required: ['product', 'run', 'arms'],
      properties: {
        product: { const: 'angel-swarm.run-result' },
        _angelSwarm: { type: 'object' },
        run: runHeaderSchema(),
        arms: { type: 'array', minItems: 3, maxItems: 3, items: armSchema() },
        comparison: { type: 'object' }
      }
    };
  }

  function schemaResultCsv() {
    return {
      $schema: DRAFT,
      $id: NS + ':schema:run-result-csv:' + VERSION,
      title: 'ANGEL SWARM run result (CSV)',
      description: 'JSON Schema cannot validate CSV text directly. This schema describes the row objects the CSV parses to, and fixes the column order the file writes them in. A consumer that parses the CSV with the header row and checks each row object against this schema has validated the product. The first six lines of the file begin with # and are a preamble to be skipped before the header row.',
      type: 'object',
      required: ['columnOrder', 'rows'],
      properties: {
        columnOrder: { type: 'array', const: RESULT_COLS },
        preambleLines: { const: 6 },
        preamblePrefix: { const: '#' },
        rows: {
          type: 'array', minItems: 3, maxItems: 3,
          items: {
            type: 'object',
            required: RESULT_COLS,
            properties: (function () {
              var p = {}, num = { type: ['integer', 'string'] };
              for (var i = 0; i < RESULT_COLS.length; i++) p[RESULT_COLS[i]] = num;
              p.arm = { enum: ['ANGEL', 'CURRENT', 'NODELIVERY'] };
              p.arm_name = { type: 'string' };
              return p;
            })()
          }
        }
      }
    };
  }

  function schemaCatalog() {
    return {
      $schema: DRAFT,
      $id: NS + ':schema:data-catalog:' + VERSION,
      title: 'ANGEL SWARM data catalog manifest',
      description: 'Everything this application publishes and everything it consumes, machine-readable.',
      type: 'object',
      required: ['catalog', 'version', 'publisher', 'produces', 'consumes'],
      properties: {
        catalog: { const: 'angel-swarm.data-catalog' },
        version: { type: 'string' },
        generatedAt: { type: 'string' },
        publisher: { type: 'object', required: ['name'], properties: { name: { type: 'string' } } },
        produces: {
          type: 'array', minItems: 1,
          items: {
            type: 'object',
            required: ['id', 'name', 'description', 'format', 'mediaType', 'schema', 'cadence'],
            properties: {
              id: { type: 'string' }, name: { type: 'string' }, description: { type: 'string' },
              format: { type: 'string' }, mediaType: { type: 'string' },
              schema: { type: 'string' }, schemaFile: { type: 'string' },
              file: { type: 'string' }, cadence: { type: 'string' },
              conformance: { type: 'string' }, delivery: { type: 'string' }
            }
          }
        },
        consumes: {
          type: 'array', minItems: 1,
          items: {
            type: 'object',
            required: ['id', 'name', 'description', 'format', 'source', 'cadence'],
            properties: {
              id: { type: 'string' }, name: { type: 'string' }, description: { type: 'string' },
              format: { type: 'string' }, source: { type: 'string' }, transport: { type: 'string' },
              direction: { const: 'inbound' }, cadence: { type: 'string' },
              status: { type: 'string' }, integrationStatus: { type: 'string' }
            }
          }
        }
      }
    };
  }

  /* ================================================= THE CATALOG MANIFEST ==
     The criterion names a data catalog, so this is one: a single file that
     lists what this application publishes and what it consumes, with a name,
     a description, a format, a schema and an update cadence on every line.
     It is generated rather than written down, so it cannot drift from the
     products it describes — every entry below is the same PRODUCTS table the
     tab renders and the download handlers dispatch on. */
  function fileName(base, ext) {
    var r = CTX && CTX.run ? CTX.run : null;
    var tag = r ? '_' + r.scenario + '_seed' + r.seed + '_T+' + Math.floor(CTX.t) : '';
    return 'angel_swarm_' + base + tag + '.' + ext;
  }

  var PRODUCTS = [
    { key: 'fhir',
      id: 'angel-swarm.casualty-care-record',
      name: 'Casualty care record set',
      shape: 'FHIR-SHAPED · NOT CONFORMANCE-TESTED',
      description: 'One FHIR R4 collection Bundle per run: a Patient per casualty, an Observation per compensatory-reserve reading, a ServiceRequest per tasking decision and a Procedure per administration. Synthetic identifiers throughout, every resource labelled HTEST.',
      format: 'JSON · FHIR R4 collection Bundle',
      mediaType: 'application/fhir+json',
      base: 'casualty_care_record_FHIR-SHAPED', ext: 'json',
      schemaKey: 'fhir.schema',
      cadence: 'On demand, once per completed run. Deterministic on the seed: the same run exports the same bytes.',
      conformance: 'FHIR-shaped. Not conformance-tested: no validator, no StructureDefinition check, no terminology binding, no profile asserted.',
      build: function () { return JSON.stringify(fhirBundle(), null, 1); } },

    { key: 'decision',
      id: 'angel-swarm.decision-record',
      name: 'Decision record',
      shape: 'FULL 64-CHARACTER DIGESTS',
      description: 'The complete hash-linked audit chain: every escalation, standing-authority dispatch, human authorisation, administration, wastage and loss, in the order it happened, each entry carrying its predecessor’s digest and its own.',
      format: 'JSON · SHA-256 hash chain',
      mediaType: 'application/json',
      base: 'decision_record', ext: 'json',
      schemaKey: 'decision.schema',
      cadence: 'On demand. The chain is append-only within a run and closed at T+180.',
      conformance: 'Tamper-evident, not tamper-proof. The chain recomputes against the text it was written over.',
      build: function () { return JSON.stringify(decisionRecord(), null, 1); } },

    { key: 'result',
      id: 'angel-swarm.run-result',
      name: 'Run result · all three arms',
      shape: 'THREE ARMS, ONE BATTLE',
      description: 'The outcome of one run on all three arms — ANGEL SWARM, CURRENT — TRIAGE & PROXIMITY, and NO FORWARD DELIVERY — folded at a stated minute, on common random numbers.',
      format: 'JSON',
      mediaType: 'application/json',
      base: 'run_result', ext: 'json',
      schemaKey: 'result.schema',
      cadence: 'On demand, at any minute of the run. A completed run is the useful one.',
      conformance: 'One seed is not a finding. The replication study on Evidence is what answers whether it is luck.',
      build: function () { return JSON.stringify(runResult(), null, 1); } },

    { key: 'resultcsv',
      id: 'angel-swarm.run-result-csv',
      name: 'Run result · CSV',
      shape: 'THREE ROWS, TWELVE COLUMNS',
      description: 'The same three arms as one row each, for a spreadsheet or an R session. Six preamble lines beginning with # precede the header row.',
      format: 'CSV · UTF-8 · comma-separated',
      mediaType: 'text/csv',
      base: 'run_result', ext: 'csv',
      schemaKey: 'resultcsv.schema',
      cadence: 'On demand, alongside the JSON. Same figures, same fold.',
      conformance: 'The schema describes the parsed row objects and fixes the column order; JSON Schema cannot validate CSV text directly.',
      build: function () { return runResultCsv(); } },

    { key: 'catalog',
      id: 'angel-swarm.data-catalog',
      name: 'Data catalog manifest',
      shape: 'WHAT IS PUBLISHED AND WHAT IS CONSUMED',
      description: 'Every product this application publishes and every source it consumes, with name, description, format, schema URI and update cadence on each. Generated from the same table the tab renders, so it cannot drift from what it describes.',
      format: 'JSON',
      mediaType: 'application/json',
      base: 'datacatalog', ext: 'json', fixedName: 'datacatalog.json',
      schemaKey: 'catalog.schema',
      cadence: 'On demand. Changes only when a product is added or removed.',
      conformance: 'A manifest, not a registration. Nothing is published to a remote catalog service by this build.',
      build: function () { return JSON.stringify(catalog(), null, 1); } }
  ];

  var SCHEMAS = {
    'fhir.schema':      { base: 'casualty_care_record.schema', build: schemaFhir },
    'decision.schema':  { base: 'decision_record.schema', build: schemaDecision },
    'result.schema':    { base: 'run_result.schema', build: schemaResult },
    'resultcsv.schema': { base: 'run_result_csv.schema', build: schemaResultCsv },
    'catalog.schema':   { base: 'datacatalog.schema', build: schemaCatalog }
  };
  var SCHEMA_ID = {
    'fhir.schema':      NS + ':schema:casualty-care-record:' + VERSION,
    'decision.schema':  NS + ':schema:decision-record:' + VERSION,
    'result.schema':    NS + ':schema:run-result:' + VERSION,
    'resultcsv.schema': NS + ':schema:run-result-csv:' + VERSION,
    'catalog.schema':   NS + ':schema:data-catalog:' + VERSION
  };

  /* ---- what this application consumes ------------------------------------
     BATDOK-J IS NAMED HERE BECAUSE IT IS THE REAL SYSTEM ON THE OTHER END OF
     THIS SOCKET, AND THE INTEGRATION STATUS IS NAMED IN THE SAME BREATH.
     BATDOK-J is the JOMIS point-of-injury and en-route care application,
     government-owned, developed by AFRL's 711th Human Performance Wing,
     selected by JOMIS in 2022 and fielding from FY26. It pairs to worn
     sensors and documents care at the point of injury, and it already speaks
     Cursor on Target across tactical networks. That makes it the plausible
     producer for the reading this application's listener accepts.

     What this application has is an INTERFACE THAT ACCEPTS THAT MESSAGE. It
     has never been tested against a real BATDOK-J. No BATDOK-J instance has
     been connected to it, no message captured from one has been replayed
     through it, and no interface control document has been agreed with the
     programme. Saying otherwise would be the easiest lie in this build to
     tell and the fastest one to be caught in. */
  var CONSUMES = [
    { id: 'cot.casualty-telemetry',
      name: 'Point-of-injury casualty telemetry',
      description: 'Compensatory reserve, heart rate and signal quality per casualty track, arriving over a receive-only socket. Where a live reading exists for a casualty it supersedes the simulated one and the tasking layer cannot tell a simulated emitter from a fielded monitor.',
      format: 'Cursor on Target XML event with the physiological values in a <detail> extension',
      source: 'BATDOK-J (JOMIS point-of-injury and en-route care application, AFRL 711th Human Performance Wing) is the plausible real producer; anything else that emits CoT to this listener is accepted identically.',
      transport: 'UDP into the launcher, republished to the page over Server-Sent Events on this origin. Receive-only. Loopback unless -cot-external is passed.',
      direction: 'inbound',
      cadence: 'Event-driven: a burst on reserve-zone change or every 45 seconds per track. Nothing at all while the link is down.',
      status: 'Off unless the launcher is started with -cot. The interface reports INGEST OFF and costs nothing when no listener exists.',
      integrationStatus: 'INTERFACE ACCEPTED, NOT INTEGRATION TESTED. This application accepts the CoT message a system like BATDOK-J emits. It has never been tested against a real BATDOK-J: no instance has been connected, no captured message has been replayed, and no interface control document has been agreed. What is demonstrated is that the reading arrives from outside this program over a socket.',
      schema: 'No ratified medical CoT schema is claimed. The values ride in CoT’s own <detail> extension mechanism, used as intended.' },

    { id: 'run.scenario',
      name: 'Scenario and platform reference data',
      description: 'Seven joint operations areas, three airframe types with published performance envelopes, five Class VIII items, and the doctrinal corpus the retrieval model quotes from.',
      format: 'JavaScript modules and JSON carried inside the build',
      source: 'app/js/sim.js, app/js/optimizer.js, app/data/ — all inside this build',
      transport: 'Read from this origin at load. No request leaves it.',
      direction: 'inbound',
      cadence: 'Fixed at build time.',
      status: 'Loaded.',
      integrationStatus: 'Ships in the build. See the Data Sources table on this destination for every file and its measured size.',
      schema: 'Documented in app/js/sim.js; not separately published.' }
  ];

  function catalog() {
    var out = {
      catalog: 'angel-swarm.data-catalog',
      version: VERSION,
      generatedAt: CTX ? instant(CTX.t) : instant(0),
      publisher: {
        name: 'ANGEL SWARM',
        description: 'Physiological-deadline blood allocation prototype for the Military Health System. Tasks autonomous medical resupply against each casualty’s time to death rather than against triage category and distance.',
        classification: 'UNCLASSIFIED // SYNTHETIC DATA // FOR DEMONSTRATION ONLY',
        origin: 'Generated in the operator’s browser. This build makes no request off its own origin; the one socket it opens is inbound.'
      },
      verticalPath: {
        description: 'The path a fielded system would take with these records: documented at the point of injury, carried vertically through OMDS — the JOMIS data-infrastructure application — into the MHS GENESIS longitudinal health record.',
        stages: ['Point of injury — casualty care documented as it happens', 'OMDS — JOMIS data infrastructure', 'MHS GENESIS — the DoD electronic health record'],
        whatThisBuildDoes: 'This application PRODUCES the record. It does not TRANSMIT it. There is no OMDS client and no MHS GENESIS client in this build, and no request leaves this origin. The record is written in the browser and handed to the operator as a file.',
        knownDeficiency: 'Per the DOT&E FY2025 JOMIS report the vertical path into the longitudinal record works; horizontal transfer between JOMIS applications is the documented deficiency. Producing a record in a shape the vertical path already carries is the useful thing a prototype can do about that.'
      },
      produces: PRODUCTS.map(function (p) {
        return {
          id: p.id,
          name: p.name,
          description: p.description,
          format: p.format,
          mediaType: p.mediaType,
          schema: SCHEMA_ID[p.schemaKey],
          schemaFile: SCHEMAS[p.schemaKey].base + '.json',
          file: p.fixedName || fileName(p.base, p.ext),
          cadence: p.cadence,
          conformance: p.conformance,
          delivery: 'Generated in-browser and downloaded as a file. Not served, not posted, not registered anywhere.'
        };
      }),
      consumes: CONSUMES
    };
    return out;
  }

  /* ---- building and handing over ----------------------------------------
     One path for every product, so a control that renders cannot be a control
     that does nothing: the same build() that the tab's byte count is measured
     from is the one the click writes out. */
  function build(key) {
    if (!ready()) return null;
    var i;
    for (i = 0; i < PRODUCTS.length; i++) {
      if (PRODUCTS[i].key === key) {
        return {
          key: key,
          name: PRODUCTS[i].fixedName || fileName(PRODUCTS[i].base, PRODUCTS[i].ext),
          mime: PRODUCTS[i].mediaType,
          text: PRODUCTS[i].build()
        };
      }
    }
    if (SCHEMAS[key]) {
      return {
        key: key,
        name: 'angel_swarm_' + SCHEMAS[key].base + '.json',
        mime: 'application/schema+json',
        text: JSON.stringify(SCHEMAS[key].build(), null, 1)
      };
    }
    return null;
  }

  /* A blob URL on this origin, clicked and revoked. Nothing is uploaded and
     no endpoint is contacted; the file exists only in this tab until the
     browser writes it to the operator’s disk. */
  function download(key) {
    var p = build(key);
    if (!p) return null;
    var url = URL.createObjectURL(new Blob([p.text], { type: p.mime + ';charset=utf-8' }));
    var a = document.createElement('a');
    a.href = url; a.download = p.name;
    document.body.appendChild(a); a.click(); a.remove();
    setTimeout(function () { URL.revokeObjectURL(url); }, 4000);
    return { name: p.name, bytes: new Blob([p.text]).size };
  }

  /* The byte count the tab prints beside each control. Measured off the same
     string the download writes, because a size that is estimated rather than
     measured is a number somebody will one day find to be wrong. */
  function sizeOf(key) {
    var p = build(key);
    return p ? new Blob([p.text]).size : 0;
  }

  window.DATAPRODUCTS = {
    VERSION: VERSION,
    setContext: setContext,
    ready: ready,
    PRODUCTS: PRODUCTS,
    SCHEMA_ID: SCHEMA_ID,
    SCHEMAS: SCHEMAS,
    CONSUMES: CONSUMES,
    catalog: catalog,
    build: build,
    download: download,
    sizeOf: sizeOf,
    fileName: function (key) { var p = build(key); return p ? p.name : null; }
  };
})();
